package com.example.bikeapp.ui.screens.profile

import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.bikeapp.data.local.AppDatabase
import com.example.bikeapp.data.model.AthleteEntity
import dagger.hilt.android.lifecycle.HiltViewModel
import jakarta.inject.Inject
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

data class AthleteFormState(
    val username: String = "",
    val firstName: String = "",
    val lastName: String = "",
    val city: String = "",
    val state: String = "",
    val country: String = "",
    val sex: String = "",
    val usernameError: String? = null,
    val firstNameError: String? = null,
    val lastNameError: String? = null,
    val isFormValid: Boolean = false,
    val error: String? = null,
    val isSuccess: Boolean = false
)

@HiltViewModel
class CreateAccountViewModel @Inject constructor(
    private val database: AppDatabase,
) : ViewModel() {
    private val _uiState = MutableStateFlow(AthleteFormState())

    // Public read-only state flow that the UI will observe
    val uiState: StateFlow<AthleteFormState> = _uiState.asStateFlow()

    // Validation and State updating
    private fun validateForm(state: AthleteFormState) {
        val isUsernameValid = state.username.isNotBlank()
        val isFirstNameValid = state.firstName.isNotBlank()
        val isLastNameValid = state.lastName.isNotBlank()

        _uiState.update { currentState ->
            currentState.copy(
                usernameError = if (isUsernameValid) null else "Username cannot be empty",
                firstNameError = if (isFirstNameValid) null else "First name cannot be empty",
                lastNameError = if (isLastNameValid) null else "Last name cannot be empty",
                isFormValid = isUsernameValid && isFirstNameValid && isLastNameValid
            )
        }
    }

    // Event Handlers for UI
    fun onUsernameChange(newValue: String) {
        _uiState.update { currentState ->
            val newState = currentState.copy(username = newValue)
            validateForm(newState)
            newState
        }
    }

    fun onFirstNameChange(newValue: String) {
        _uiState.update { currentState ->
            val newState = currentState.copy(firstName = newValue)
            validateForm(newState)
            newState
        }
    }

    fun onLastNameChange(newValue: String) {
        _uiState.update { currentState ->
            val newState = currentState.copy(lastName = newValue)
            validateForm(newState)
            newState
        }
    }

    /**
     * This function is called when the user clicks the "Save" button.
     * It should only proceed if the form is valid.
     */
    fun saveAthlete() {
        if (_uiState.value.isFormValid) {
            viewModelScope.launch {
                val currentState = _uiState.value
                val newAthlete = AthleteEntity(
                    id = 0, // This will be auto-generated by the database
                    username = currentState.username,
                    firstname = currentState.firstName,
                    lastname = currentState.lastName,
                    city = null, // Or get from other state variables
                    state = null,
                    country = null,
                    sex = null
                )

                Log.d("CreateAccountViewModel", "Saving new athlete: $newAthlete")

                try {
                    database.athleteDao().insertAthlete(newAthlete)
                    Log.d("CreateAccountViewModel", "Athlete saved successfully")

                    _uiState.value = _uiState.value.copy(isSuccess = true, error = null)
                } catch (e: Exception) {
                    Log.e("CreateAccountViewModel", "Error saving new athlete", e)

                    _uiState.value =
                        _uiState.value.copy(isSuccess = false, error = "Error saving athlete")
                }
            }
        }
    }
}